### ISSUE TITLE
query_ returns too few rows

### ISSUE THREAD

**Issue by peti** [phadej/postgresql-simple#32]
It appears that `query_` silently drops results from queries. I just ran a (somewhat complex) SELECT query and got a list with 769 elements back. Then I run the exact same query in the psql shell, and it returns a table with 1136 rows. I'm pretty sure that is not what is supposed to happen?

I'll try using `forEach_` instead. Maybe that works better.

I'm using postgresql-simple-0.6.2 with postgresql-11.

**Comment by peti** [comment]
`forEach_` behaves the exact same way. I get 769 rows, then the stream ends without any error (even though I can clearly tell that rows are missing).

**Comment by phadej** [comment]
without a reproducible test-case we cannot fix this.

As you say you use `query_` I assume query is not parametrised, which is good. We can be quite sure that what you run from `psql` and via library is the same query.

Please look into your result sets and try to find out what kind of rows are omitted from the result, maybe there's a hint what goes wrong

**Comment by peti** [comment]
Nevermind, there is no bug. I edited the query in my Haskell source code and then printed it in ghci to copy&paste it into the psql window. I forgot to reload the code, though, so the query I executed in psql was subtly different from the one the Haskell code ran when I compiled and executed the binary. I am sorry for the noise.
