### ISSUE TITLE
Levity Polymorphic Result Consumer in fold_ ?

### ISSUE THREAD

**Issue by nineonine** [phadej/postgresql-simple#35]
Is it possible to implement levity polymorphic consumer in [fold_](https://hackage.haskell.org/package/postgresql-simple-0.6.2/docs/Database-PostgreSQL-Simple.html#v:fold_) and other folding variants?

**Comment by nineonine** [comment]
oops sorry I didn't notice it was a fork :D

**Comment by phadej** [comment]
This is not a "fork", this is the maintained version as Hackage metadata says. I'll send a message to GitHub support to break the fork status.

**Comment by nineonine** [comment]
Is this place suitable to ask this question?

**Comment by phadej** [comment]
of course you can ask questions, but I don't understand your motivation for "levity polymorphic result consumer", do you want something like:

```haskell
levityPolymorphicFold_
    :: forall (a :: TYPE rep, r) . (FromRow r)
    => Connection
    -> Query                  -- ^ Query.
    -> a                      -- ^ Initial state for result consumer.
    -> (a -> r -> IO a)       -- ^ Result consumer. -- this is wrong, kinds don't match one have to open IO
    -> IO a
```

I'm not sure how that would work, and if it's really worth any pain, as perfectly GHC will unbox stuff for in worker/wrapper transform.

**Comment by nineonine** [comment]
Yes this is exactly what I wanted!
Is `worker/wrapper` always being applied (without `-O`)?
Is there a was to verify this?
Thanks!

**Comment by phadej** [comment]
worker/wrapper is an optimization, so is applied only if optimizations is on (with `-O`). Yet, if you compile without optimizations, what's the point of having this piece of code levity polymorphic?

I simply don't understand the motivation, where you would use it?

Performance wise, it's really unrelevant, as parsing the database responses will take a lot more time in comparison, so a possible additional box allocation won't be noticeable.

**Comment by nineonine** [comment]
I see. I guess I thought it was possible to use unboxed tuples in `a` but I think you can't do this since `a` is also a function argument.
Thanks for the explanation!
